version: '3'

services:
  app:
    build: .
    env_file: .env
    depends_on:
      db:
        condition: service_healthy
    stdin_open: true
    tty: true
    ports:
      - 127.0.0.1:8080:8080

  db:
    image: postgres:12-alpine
    env_file: .env
    volumes:
      - .data:/var/lib/postgresql/data
      - ./scripts/postgres-enable-uuid-extension.sh:/docker-entrypoint-initdb.d/postgres-enable-uuid-extension.sh
    ports:
      - 127.0.0.1:5432:5432
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U $POSTGRES_USER -d $POSTGRES_DB']
      interval: 5s
      timeout: 5s

  test_db:
    image: postgres:12-alpine
    environment:
      POSTGRES_USER: "app"
      POSTGRES_DB: "app_test"
      POSTGRES_PASSWORD: "password"
    volumes:
      - ./scripts/postgres-enable-uuid-extension.sh:/docker-entrypoint-initdb.d/postgres-enable-uuid-extension.sh
    ports:
      - 127.0.0.1:5433:5432
