name: Tests

on: [push, pull_request]

jobs:
  tests:
    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12
        env:
          POSTGRES_USER: app
          POSTGRES_PASSWORD: password
          POSTGRES_DB: app_test
        ports: ['5433:5432']
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - name: Enable PostgreSQL Extensions
        run: psql --host=localhost --port=5433 -U app app_test -tc 'CREATE EXTENSION "uuid-ossp";'
        env:
          PGPASSWORD: password

      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.19

      - name: Build
        run: make build

      - name: Test
        run: make test

      - name: Build Docker Image
        run: make docker-build
